Add: Generate.bcrypt.hash.md
wg-easy/wg-easy pull request #1135
Opened 2024-06-26 11:03 UTC by pheiduck

Thanks to: @mathys-lopinto

2024-06-26 16:55 UTC, mathys-lopinto approved these changes

2024-06-27 11:45 UTC, kaaax0815 commented
Consider adding a simple one-liner, where you don't have to create a file

2024-06-27 13:03 UTC, mathys-lopinto requested changes
Enhance bcrypt doc: add one-liner, usage info, and assert
- Add one-liner command for quick execution
- Include dedicated paragraph on using the output
- Implement assert to prevent bcrypt limitation issues
- Comment the python script
 Improves clarity and usability of bcrypt documentation

2024-06-27 18:33 UTC, pheiduck commented
Okay, I will merge this now. After that you can open a PR with adjustments guys. ;)

2024-06-27 18:34 UTC, merged