Prometheus metrics
wg-easy/wg-easy pull request #1299
Opened 2024-08-19 18:07 UTC by AKEB

## Description

This update adds metrics for prometheus. 
Dashboard for grafana can be imported by id [21733](https://grafana.com/grafana/dashboards/21733-wireguard/) or with JSON  
[WireGuard-1724075031304.json](https://github.com/user-attachments/files/16661195/WireGuard-1724075031304.json)

## Motivation and Context

https://github.com/wg-easy/wg-easy/issues/1285

## How has this been tested?

On my server

## Screenshots (if appropriate):

![Screenshot at Aug 19 16-41-57](https://github.com/user-attachments/assets/dae8f9cc-04ff-4f1c-bb5d-5558393b5603)
![Screenshot at Aug 19 16-55-04](https://github.com/user-attachments/assets/9431bb7d-34aa-40b9-995c-f24948523d79)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2024-08-19 19:32 UTC, pheiduck commented
@AKEB any reason why closed and resubmitted?

2024-08-19 19:34 UTC, pheiduck commented
> Dashboard for grafana can be imported by id [21733](https://grafana.com/grafana/dashboards/21733-wireguard/) or with JSON

Very nice!

2024-08-20 07:46 UTC, AKEB commented
> @AKEB any reason why closed and resubmitted?

I made a mistake in the comet commentary there. So I rearranged

2024-08-20 14:52 UTC, pheiduck commented
> lgtm. but please stop fixing other stuff (like formating) completely unrelated to your feature

Or even better split this into 2 PRs please! @AKEB

2024-08-21 13:01 UTC, AKEB commented
- job_name: wireguard
    scrape_interval: 30s
    scrape_timeout: 20s
    static_configs:
    - targets:
      - 'localhost:51281'

2024-08-21 14:57 UTC, AKEB commented
> No I mean if Password in wg-easy is set. Right now Prometheus can't scrape the endpoint as it would require a valid session or the correct headers
> @AKEB uses authentik according to his linked repo therefore he probably didn't test how it works if `PASSWORD_HASH` is set. (I could be completely wrong tho)

No. You're completely wrong. The password is only needed if the path contains /api/ 
And metrics for Prometheus are located in the path /metrics

2024-08-21 17:14 UTC, pheiduck commented
If the feature should be accepted a Rebase is needed, as I sayed before due, all new PRs should be at the top of older commits.

2024-08-22 08:18 UTC, AKEB commented
> Yes ok, I think that that every route underneath the middleware is grouped logically to be handled with that middleware. But shouldn't the route be secured? Anybody just knowing your throughput, which clients are connected etc seems like a bad idea

If you are afraid, you don't need to use it. Or you can do separately as suggested by other users on the net. There are many solutions on github

2024-08-22 08:51 UTC, AKEB commented
> > If you are afraid, you don't need to use it. Or you can do separately as suggested by other users on the net. There are many solutions on github. For example https://github.com/tolkonepiu/wg-easy-extended
> 
> I believe the PR makes sense as it doesn’t add a significant maintenance burden and introduces a useful feature. However, I have concerns about its security. Therefore, it should either:
> 
> * Be disabled by default, with clear communication to the user that enabling this feature is insecure.
> * Be protected behind authentication.

I added a separate port for prometheus metrics. It's safer that way. You can keep it open, but give access only to prometheus itself.

2024-08-22 14:10 UTC, AKEB commented on src/lib/Server.js
> +        if (req.url.startsWith('/metrics') && user.pass) {
```
// WireGuard
    app.use(
      fromNodeMiddleware((req, res, next) => {
        if (!requiresPassword || !req.url.startsWith('/api/')) {
          return next();
        }

        if (req.session && req.session.authenticated) {
          return next();
        }

        if (req.url.startsWith('/api/') && req.headers['authorization']) {    # The Same
          if (isPasswordValid(req.headers['authorization'], PASSWORD_HASH)) {
            return next();
          }
          return res.status(401).json({           # This ERROR!!! 500
            error: 'Incorrect Password',
          });
        }

        return res.status(401).json({           # This ERROR!!! 500
          error: 'Not Logged In',
        });
      }),
    );
```

2024-08-22 22:33 UTC, AKEB commented
@pheiduck Is there anything else you need from me?

2024-08-23 07:54 UTC, kaaax0815 requested changes

2024-08-23 07:54 UTC, kaaax0815 commented on README.md
> +* * Prometheus metrics support
* is doubled

2024-08-23 08:26 UTC, kaaax0815 approved these changes

2024-08-23 09:48 UTC, pheiduck approved these changes

2024-08-23 09:58 UTC, AKEB commented on src/lib/Server.js
> +        if (req.url.startsWith('/metrics') && user.pass) {
There is no res.status() function and at this point the code returns a status of 500 instead of 401

2024-08-23 10:07 UTC, kaaax0815 commented on src/lib/Server.js
> +        if (req.url.startsWith('/metrics') && user.pass) {
understood.
we are currently doing a rewrite using nuxt and typescript #1244 where this isn't the case. so i think its fine by now

2024-08-23 10:10 UTC, merged

2025-11-05 15:22 UTC, Surgical17 commented
Hi There @AKEB 

Can you confirm if this is working for V15?

I set up Victoria Metrics (Since it is a drop in replacement for Prometheus) I setup the config according the the Docs on the wg easy website but i can only pull these metrics (yes I did enable it in Admin Panel)

<img width="1195" height="557" alt="image" src="https://github.com/user-attachments/assets/26719e13-ebd3-40e1-af80-4114b98d27ad" />