WIP add database
wg-easy/wg-easy pull request #1330
Opened 2024-08-29 15:23 UTC by tetuaoro

### Just to get your opinion

I add `in-memory` database provider and move PASSWORD_HASH from `env` to the user interface *(not `/setting` page)*. If no `users` exist in the database, you will be redirected to the first `/setup` page.

### Changes

- [x] add `in-memory` database
- [x] first setup page
- [x] create new account
- [x] login with username and password.

***Work in progress.***

2024-08-29 20:41 UTC, kaaax0815 requested changes

2024-08-29 20:41 UTC, kaaax0815 commented on src/server/api/session.post.ts
> +    });
this should be made more secure. this would allow bad actors to probe correct usernames.
also timing should be considered

2024-08-29 20:41 UTC, kaaax0815 commented on src/server/api/lang.get.ts
> +  return await Database.getLang();
await is not needed. as returning a Promise is fine

2024-08-29 20:41 UTC, kaaax0815 commented on src/server/api/account/new.post.ts
> +    // TODO use zod
should be done. before merging. also please use `TODO: message_here`

2024-08-29 20:41 UTC, kaaax0815 commented on src/ports/user/model.ts
> +}
personally think enums are not very good in typescript [^1]

[^1]: https://graphqleditor.com/blog/enums-are-still-bad/

2024-08-29 20:41 UTC, kaaax0815 commented on src/ports/types.ts
> +export type Boolean = boolean;
Id is a uuid therefore a string.
Also I don't think there is a reason for creating a type alias for basic types

2024-08-29 20:41 UTC, kaaax0815 commented on src/ports/types.ts
> +  wgPreUp: Command;
`wgPreUp: string` is totally fine

2024-08-29 20:41 UTC, kaaax0815 commented on src/ports/types.ts
> +export enum ChartType {
see other comment about enums

2024-08-29 20:41 UTC, kaaax0815 commented on src/ports/database.ts
> +
question about the folder structure.
what does `ports` mean in this context?
maybe everything database related should be moved into a single folder to not "pollute" the folder structure

2024-08-29 20:41 UTC, kaaax0815 commented on src/ports/database.ts
> + * *Note : Throw with `DatabaseError` to ensure API handling errors.*
use jsdoc for that

2024-08-29 20:41 UTC, kaaax0815 commented on src/pages/setup.vue
> +const password = ref<string>();
its common practive in this repo to use null as a initial value

2024-08-29 20:41 UTC, kaaax0815 commented on src/pages/login.vue
> +const username = ref<string>();
use null as initial value

2024-08-29 20:41 UTC, kaaax0815 commented on src/ports/types.ts
> +export type Identity<T> = ID | T;
Why not use string directly?

2024-08-29 20:41 UTC, kaaax0815 commented on src/ports/database.ts
> +    'Password does not meet the strength requirements. It must be at least 12 characters long, with at least one uppercase letter, one lowercase letter, one number, and one special character.';
this should probably done using zod. or as a key for i18n

2024-08-29 20:41 UTC, kaaax0815 commented on src/ports/database.ts
> +  abstract saveUser(_user: User): Promise<void>;
avoid using underscore for variables

2024-08-29 20:41 UTC, kaaax0815 commented on src/adapters/database/inmemory.ts
> +const INMDP_DEBUG = debug('InMemoryDP');
`InMemoryDB` makes more sense imo

2024-08-29 20:44 UTC, kaaax0815 commented
Very nice work.
Do you have some thoughts that will need to be done. I could create a issue tracker for that

2024-08-30 12:26 UTC, tetuaoro commented
> Do you have some thoughts that will need to be done.

Yes, what's the database provider are we going to use ? I'm going to move all the `env`s to the database first.

2024-08-30 13:10 UTC, kaaax0815 commented
> Yes, what's the database provider are we going to use ? I'm going to move all the `env`s to the database first.

Good question. Have you tried out any? lowdb works on all platforms I believe

2024-08-30 13:15 UTC, tetuaoro commented
> Good question. Have you tried out any? lowdb works on all platforms I believe

Ok

2024-08-30 13:35 UTC, kaaax0815 requested changes

2024-08-30 13:35 UTC, kaaax0815 commented on src/adapters/database/inmemory.ts
> +  users: Array<User>;
Use `User[]` Syntax

2024-08-30 13:35 UTC, kaaax0815 commented on src/ports/system/model.ts
> +import type { SessionConfig } from 'h3';
This File only adds typings. Maybe model and interface should be merged. As we don't follow a mvc-like pattern

2024-08-30 13:35 UTC, kaaax0815 commented on src/ports/types.ts
> +export type Undefined = null | undefined | 0 | '';
Please don't do that. Undefined should be clearly defined. `null` or `undefined` depending on use case. No type coercion

2024-08-30 13:35 UTC, kaaax0815 commented on src/server/api/lang.get.ts
> +export default defineEventHandler(async (event) => {
async can be removed here

2024-08-30 13:35 UTC, kaaax0815 commented on src/package.json
> +    "uuid": "^10.0.0",
cant find a reference to a import for this package. Should be replaced by `crypto.randomUUID`

2024-08-30 13:47 UTC, kaaax0815 commented
I think this pr should only add the move to a database. Stuff noted in #1333 and moving all env to the ui should be done in a later stage to avoid too much work in #1333

2024-08-30 14:22 UTC, kaaax0815 commented
Please move database from services and repositories into its own database folder

2024-08-30 15:10 UTC, kaaax0815 commented on src/server/middleware/setup.ts
> +    return sendRedirect(event, '/setup', 302);
this runs on every request but is only needed once. is there a better way to do this?

2024-08-30 15:10 UTC, kaaax0815 commented on src/localeDetector.ts
> +// https://i18n.nuxtjs.org/docs/guide/server-side-translations
is this really needed?

2024-08-30 15:13 UTC, tetuaoro commented
> I think this pr should only add the move to a database. Stuff noted in #1333 and moving all env to the ui should be done in a later stage to avoid too much work in #1333

Ok

2024-08-30 16:59 UTC, kaaax0815 commented
i think adding a "proper" persistent database should be handled by this pr. then i'll merge it

2024-08-31 11:34 UTC, tetuaoro commented
actually, the database assume log in with a username & a password

### TODO
- [x] UI `/setup` page
- [x] timing session post
- [x] re-export types *(not required)*
- [x] compute next ip based on CIDR, not with `x` : *10.8.0.x*.

2024-08-31 21:21 UTC, kaaax0815 commented on src/localeDetector.ts
> +// https://i18n.nuxtjs.org/docs/guide/server-side-translations
@tetuaoro

2024-08-31 21:34 UTC, kaaax0815 commented on .gitignore
> +db.json
this shouldn't be needed as the file should be inside `/etc/wireguard`

2024-08-31 21:35 UTC, kaaax0815 commented
lgtm (some thinks still can be improved but its more nitpicking than actual improvements)

2024-09-01 02:29 UTC, tetuaoro commented
> @tetuaoro What do you want to add to this repo? Because the TODO you commented are for separate prs

Yes

2024-09-01 07:10 UTC, merged