Setup UI
wg-easy/wg-easy pull request #1409
Opened 2024-09-15 13:50 UTC by tetuaoro

Error handling with `Toast` component.

2024-09-15 13:53 UTC, tetuaoro commented
wow build step is fast

2024-09-15 13:59 UTC, tetuaoro commented on src/app/pages/me.vue
I'll update `components` later as I didn't see that `radix-vue` had been added.

2024-09-16 05:38 UTC, kaaax0815 commented on src/app/pages/me.vue
Could u also make this pr against https://github.com/kaaax0815/wg-easy/tree/feat-admin

2024-09-16 12:58 UTC, tetuaoro commented on src/app/pages/me.vue
Can't find your repo

![image](https://github.com/user-attachments/assets/a3f71035-090a-4a5b-ae58-7f1b2e20fffb)

2024-09-16 13:04 UTC, kaaax0815 commented on src/app/pages/me.vue
You can create it here https://github.com/kaaax0815/wg-easy/compare/feat-admin...tetuaoro:wg-easy:admin-ui

2024-09-16 14:02 UTC, kaaax0815 requested changes

2024-09-16 14:02 UTC, kaaax0815 commented on src/app/components/error/Toast.vue
> +const autoCloseToast = props.duration ? Number(props.duration) : 12000; // 12 seconds
https://www.radix-vue.com/components/toast#custom-duration

2024-09-16 14:05 UTC, tetuaoro commented on src/app/components/error/Toast.vue
> +const autoCloseToast = props.duration ? Number(props.duration) : 12000; // 12 seconds
thx

2024-09-16 14:14 UTC, kaaax0815 commented
Handled in https://github.com/kaaax0815/wg-easy/pull/4

2024-09-16 14:14 UTC, closed without merging