Fixes #327
wg-easy/wg-easy pull request #328
Opened 2022-07-26 01:28 UTC by archont94

2022-07-26 03:17 UTC, eandersons requested changes

2022-07-26 03:17 UTC, eandersons commented on src/lib/WireGuard.js
> +                throw new Error('WireGuard exited with the error: Cannot find device "wg0"\nThis means, that even wireguard-go does not work!\nThis usually means that you didn\'t mounted /dev/net/tun
Grammar: `didn't mounted` > `didn't mount`.

2022-07-26 09:42 UTC, WeeJeWel commented
Would be better to download & make `wireguard-go` ourselves instead of relying on someone's docker image.

2022-07-26 12:20 UTC, archont94 commented
> Would be better to download & make `wireguard-go` ourselves instead of relying on someone's docker image.

External dependencies removed.

2022-09-16 07:31 UTC, gaby commented
@archont94 @WeeJeWel  Alpine already publishes an official package for `wireguard-go`. It's in the edge tag.

```
FROM alpine:edge

RUN apk update && apk add wireguard-go
```

Package link: https://pkgs.alpinelinux.org/package/edge/testing/x86_64/wireguard-go

2022-12-16 21:01 UTC, rudasn commented
> @archont94 @WeeJeWel Alpine already publishes an official package for `wireguard-go`. It's in the edge tag.
> 
> ```
> FROM alpine:edge
> 
> RUN apk update && apk add wireguard-go
> ```
> 
> Package link: https://pkgs.alpinelinux.org/package/edge/testing/x86_64/wireguard-go

I'm not familiar with alpine, how stable is the edge tag? Is there a time frame for when wireguard-go will be included in latest?

2024-01-03 22:13 UTC, pheiduck commented
A better solution is build here: https://github.com/wg-easy/wg-easy/pull/702
This can be closed.

2024-01-03 22:13 UTC, closed without merging